# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-14 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='description_long',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='avatar',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='address',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='description_short',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title_short',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='logo',
        ),
        migrations.AddField(
            model_name='actor',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actor',
            name='share_contact_ref',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='description_long',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_short',
            field=models.TextField(default='', max_length=240),
        ),
        migrations.AddField(
            model_name='event',
            name='subtitle',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='experience',
            name='featured_image_txt',
            field=models.TextField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='description_long',
            field=tinymce.models.HTMLField(default='<h3>Titre</h3></hgroup><p>Paragraph</p><h3>Titre</h3></hgroup><p>Paragraph</p>', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description_long',
            field=tinymce.models.HTMLField(default='<h3>Titre</h3></hgroup><p>Paragraph</p><h3>Titre</h3></hgroup><p>Paragraph</p>', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='url',
            field=models.URLField(blank=True, max_length=240),
        ),
    ]
