# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-14 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0002_auto_20170214_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='categories',
            field=models.ManyToManyField(null=True, to='appli.Category'),
        ),
    ]
