# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-14 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0003_auto_20170214_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='categories',
            field=models.ManyToManyField(to='appli.Category'),
        ),
    ]
