# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0004_auto_20170214_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='image',
            field=models.ManyToManyField(to='appli.ExperienceImage'),
        ),
    ]
