# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0005_experience_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='image',
        ),
        migrations.AddField(
            model_name='experienceimage',
            name='experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appli.Experience'),
        ),
    ]
