# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0006_auto_20170215_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Ville'},
        ),
        migrations.AlterField(
            model_name='actorimage',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli.Actor'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='featured_image_txt',
            field=models.TextField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='experience',
            name='subtitle',
            field=models.CharField(max_length=240, verbose_name='sous-titre'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=120, verbose_name='titre'),
        ),
    ]
