# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0007_auto_20170215_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engagement',
            options={'verbose_name': 'Contact'},
        ),
        migrations.AlterModelOptions(
            name='participation',
            options={'verbose_name': 'Participant'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='title',
        ),
        migrations.AddField(
            model_name='contact',
            name='description_long',
            field=models.CharField(default='', max_length=240, verbose_name='description compl\xe9ments'),
        ),
        migrations.AddField(
            model_name='contact',
            name='description_short',
            field=models.CharField(default='', max_length=120, verbose_name='description courte'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='address',
            field=models.CharField(blank=True, max_length=240, verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='city',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='appli.City', verbose_name='ville'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='description_long',
            field=tinymce.models.HTMLField(default='<h3>Titre</h3></hgroup><p>Paragraph</p><h3>Titre</h3></hgroup><p>Paragraph</p>', null=True, verbose_name='description longue'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='description_short',
            field=models.CharField(max_length=120, verbose_name='description courte'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='\xe0 la une'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='actor/featured_image', verbose_name='image de couverture'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=120, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='share_contact_ref',
            field=models.BooleanField(default=False, verbose_name='autorise la transmission des coordonn\xe9es des contacts'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli.Actor', verbose_name='acteur'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='courriel'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=120, verbose_name='pr\xe9nom'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=120, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='t\xe9l\xe9phone'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appli.City', verbose_name='ville'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date de cr\xe9ation'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description_long',
            field=tinymce.models.HTMLField(default='<h3>Titre</h3></hgroup><p>Paragraph</p><h3>Titre</h3></hgroup><p>Paragraph</p>', null=True, verbose_name='Description longue'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description_short',
            field=models.TextField(max_length=240, verbose_name='Description courte'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='\xe0 la une'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='experience', verbose_name='image de couverture'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='featured_image_txt',
            field=models.TextField(blank=True, default='', max_length=240, verbose_name='l\xe9g\xe9nde, cr\xe9dit photo...'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='date de mise \xe0 jour'),
        ),
    ]
