# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 10:35
from __future__ import unicode_literals

from django.db import migrations, models
#import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0008_auto_20170216_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='description_long',
        ),
        migrations.AlterField(
            model_name='actor',
            name='tags',
            field=models.ManyToManyField(null=True, to='appli.Tag'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='rank',
            field=models.PositiveIntegerField(verbose_name='n\xb0 ordre'),
        ),
        #migrations.AlterField(
        #    model_name='experience',
        #    name='description_long',
        #    field=tinymce.models.HTMLField(default='<h3>Titre</h3></hgroup><p>Paragraph</p><h3>Titre</h3></hgroup><p>Paragraph</p>', null=True, verbose_name='description longue'),
        #),
        migrations.AlterField(
            model_name='experience',
            name='description_short',
            field=models.TextField(max_length=240, verbose_name='description courte'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='featured_image_txt',
            field=models.TextField(blank=True, default='', max_length=240, verbose_name='l\xe9gende, cr\xe9dit photo...'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='rank',
            field=models.PositiveIntegerField(verbose_name='n\xb0 ordre'),
        ),
    ]
