# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0009_auto_20170216_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='tags',
            field=models.ManyToManyField(blank=True, to='appli.Tag'),
        ),
    ]
