# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0010_auto_20170216_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='categories',
        ),
        migrations.AlterModelOptions(
            name='actorimage',
            options={'verbose_name': 'Image_Acteur'},
        ),
        migrations.AlterModelOptions(
            name='experienceimage',
            options={'verbose_name': 'Image_Experience'},
        ),
        migrations.RemoveField(
            model_name='actor',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='tags',
        ),
        migrations.AlterField(
            model_name='actorimage',
            name='file',
            field=models.ImageField(upload_to='images', verbose_name='fichier'),
        ),
        migrations.AlterField(
            model_name='actorimage',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='titre, cr\xe9dit...'),
        ),
        migrations.AlterField(
            model_name='city',
            name='insee',
            field=models.CharField(max_length=5, verbose_name='code INSEE de la commune'),
        ),
        migrations.AlterField(
            model_name='event',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de cr\xe9ation'),
        ),
        migrations.AlterField(
            model_name='event',
            name='deadline_date',
            field=models.DateField(verbose_name='date de fin de publication'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_long',
            field=tinymce.models.HTMLField(null=True, verbose_name='decription longue'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_short',
            field=models.TextField(default='', max_length=240, verbose_name='description courte'),
        ),
        migrations.AlterField(
            model_name='event',
            name='featured',
            field=models.BooleanField(verbose_name='\xe0 la une'),
        ),
        migrations.AlterField(
            model_name='event',
            name='featured_image',
            field=models.ImageField(upload_to='events/featured_image', verbose_name='image de couverture'),
        ),
        migrations.AlterField(
            model_name='event',
            name='publication_date',
            field=models.DateField(verbose_name='date de publication'),
        ),
        migrations.AlterField(
            model_name='event',
            name='subtitle',
            field=models.CharField(default='', max_length=240, verbose_name='sous-titre'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=120, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='event',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date de mise \xe0 jour'),
        ),
        migrations.AlterField(
            model_name='experienceimage',
            name='file',
            field=models.ImageField(upload_to='images', verbose_name='fichier'),
        ),
        migrations.AlterField(
            model_name='experienceimage',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='titre, cr\xe9dit...'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='experiencetag',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli.Experience'),
        ),
    ]
