# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0012_actortag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Localisation'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='featured',
        ),
    ]
