# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0014_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Nom de la commune'),
        ),
    ]
