# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0016_auto_20170224_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_long',
            field=markdownx.models.MarkdownxField(null=True, verbose_name='decription longue'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='description_long',
            field=markdownx.models.MarkdownxField(default='#### Titre', null=True, verbose_name='description longue'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name='compl\xe9ment'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description_long',
            field=markdownx.models.MarkdownxField(default='#### Titre', null=True, verbose_name='description longue'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='tags',
            field=models.ManyToManyField(to='appli.ExperienceTag'),
        ),
    ]
