# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0018_auto_20170308_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencetagorder',
            name='order',
            field=models.PositiveIntegerField(null=True, verbose_name='n\xb0 ordre'),
        ),
    ]
