# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0020_auto_20170308_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actortagorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='experiencetagorder',
            name='order',
        ),
    ]
